global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "dailyfit-backend"
    static_configs:
      - targets: ["backend:8001"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9091"]
