apiVersion: 1

datasources:
  - name: DailyFit MySQL
    type: mysql
    uid: dailyfit-mysql
    access: proxy
    url: dailyfit-mysql:3306
    database: dailyfit
    user: root
    secureJsonData:
      password: ${DB_PASSWORD}
    isDefault: false
    version: 1
    jsonData:
      tlsSkipVerify: true
